mv /var/www/app/app/Template/board/tooltip_subtasks.org /var/www/app/app/Template/board/tooltip_subtasks.php
mv /var/www/app/app/Helper/ProjectRoleHelper.org /var/www/app/app/Helper/ProjectRoleHelper.php
mv /var/www/app/app/Model/ProjectRoleRestrictionModel.org /var/www/app/app/Model/ProjectRoleRestrictionModel.php
mv /var/www/app/app/Controller/TaskModificationController.org /var/www/app/app/Controller/TaskModificationController.php
mv /var/www/app/app/Template/task/sidebar.org /var/www/app/app/Template/task/sidebar.php
mv /var/www/app/app/Template/task/dropdown.org /var/www/app/app/Template/task/dropdown.php
mv /var/www/app/app/Template/task/show.org /var/www/app/app/Template/task/show.php
mv /var/www/app/app/Template/task_external_link/table.org /var/www/app/app/Template/task_external_link/table.php
mv /var/www/app/app/Template/task_file/files.org /var/www/app/app/Template/task_file/files.php
mv /var/www/app/app/Template/task_file/images.org /var/www/app/app/Template/task_file/images.php
mv /var/www/app/app/Template/subtask/menu.org /var/www/app/app/Template/subtask/menu.php
mv /var/www/app/app/Template/subtask/show.org /var/www/app/app/Template/subtask/show.php
